# Generated by Django 4.1.6 on 2023-02-24 09:55

import blog.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElecUnits',
            fields=[
                ('no', models.AutoField(db_column='No', primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('prevdateinmillisec', blog.fields.myTimestampField(blank=True, db_column='prevDateInMilliSec', null=True)),
                ('nextdateinmillisec', blog.fields.myTimestampField(blank=True, db_column='nextDateInMilliSec', null=True)),
                ('prevreading', models.IntegerField(blank=True, db_column='prevReading', null=True)),
                ('nextreading', models.IntegerField(blank=True, db_column='nextReading', null=True)),
                ('price', models.CharField(blank=True, max_length=15, null=True)),
                ('calcstr', models.CharField(blank=True, db_column='calcStr', max_length=100, null=True)),
                ('isitbill', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], db_column='isItBill', default=0)),
            ],
            options={
                'db_table': 'elecUnits',
            },
        ),
    ]
