# Generated by Django 3.2.16 on 2023-01-26 12:26

import blog.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elecunits',
            name='nextdateinmillisec',
            field=blog.fields.myTimestampField(blank=True, db_column='nextDateInMilliSec', null=True),
        ),
    ]
